// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI94WP-GtqCMAeFtHzDrRlrLUi8hE8704',
    appId: '1:312444405728:web:ad4c761d00f4dfa3bf0d85',
    messagingSenderId: '312444405728',
    projectId: 'pratice-ad61e',
    authDomain: 'pratice-ad61e.firebaseapp.com',
    storageBucket: 'pratice-ad61e.firebasestorage.app',
    measurementId: 'G-72812WJ77K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFiDCQ-f7xbeK6uAmeG8rGb2H5CVTkIOo',
    appId: '1:312444405728:android:d2033b94ec4d2020bf0d85',
    messagingSenderId: '312444405728',
    projectId: 'pratice-ad61e',
    storageBucket: 'pratice-ad61e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBudSYazWx1mw0o0sRlg06N8vrRMQckths',
    appId: '1:312444405728:ios:0834ef752d3b47fbbf0d85',
    messagingSenderId: '312444405728',
    projectId: 'pratice-ad61e',
    storageBucket: 'pratice-ad61e.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBudSYazWx1mw0o0sRlg06N8vrRMQckths',
    appId: '1:312444405728:ios:0834ef752d3b47fbbf0d85',
    messagingSenderId: '312444405728',
    projectId: 'pratice-ad61e',
    storageBucket: 'pratice-ad61e.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI94WP-GtqCMAeFtHzDrRlrLUi8hE8704',
    appId: '1:312444405728:web:bb778573eeb3541ebf0d85',
    messagingSenderId: '312444405728',
    projectId: 'pratice-ad61e',
    authDomain: 'pratice-ad61e.firebaseapp.com',
    storageBucket: 'pratice-ad61e.firebasestorage.app',
    measurementId: 'G-736G0VPZQX',
  );
}
